_format_version: "3.0"
_transform: true

services:

  - name: vitals-trends-service
    url: http://host.docker.internal:8001
    routes:
      - name: vitals-trends-route
        paths:
          - /mcp/clinical/vitals-trends/dev
        strip_path: true
    plugins:
      - name: request-transformer
        config:
          replace:
            uri: /mcp
      - name: jwt
        config:
          uri_param_names: []
          cookie_names: []
          key_claim_name: iss
          secret_is_base64: false
      - name: rate-limiting
        config:
          minute: 60
          policy: local
          fault_tolerant: true
          hide_client_headers: false

  - name: labs-diagnoses-service
    url: http://labs-diagnoses:8002
    routes:
      - name: labs-diagnoses-route
        paths:
          - /mcp/clinical/labs-diagnoses/dev
        strip_path: false
    plugins:
      - name: jwt
        config:
          uri_param_names: []
          cookie_names: []
          key_claim_name: iss
          secret_is_base64: false
      - name: rate-limiting
        config:
          minute: 60
          policy: local
          fault_tolerant: true
          hide_client_headers: false

  - name: medications-interactions-service
    url: http://medications-interactions:8003
    routes:
      - name: medications-interactions-route
        paths:
          - /mcp/clinical/medications-interactions/dev
        strip_path: false
    plugins:
      - name: jwt
        config:
          uri_param_names: []
          cookie_names: []
          key_claim_name: iss
          secret_is_base64: false
      - name: rate-limiting
        config:
          minute: 30
          policy: local
          fault_tolerant: true
          hide_client_headers: false

  - name: clinical-notes-search-service
    url: http://clinical-notes-search:8004
    routes:
      - name: clinical-notes-search-route
        paths:
          - /mcp/clinical/clinical-notes-search/dev
        strip_path: false
    plugins:
      - name: jwt
        config:
          uri_param_names: []
          cookie_names: []
          key_claim_name: iss
          secret_is_base64: false
      - name: rate-limiting
        config:
          minute: 30
          policy: local
          fault_tolerant: true
          hide_client_headers: false

plugins:
  - name: opentelemetry
    config:
      endpoint: http://jaeger:4317
      resource_attributes:
        service.name: kong-gateway

consumers:
  - username: runtime-agent
    jwt_secrets:
      - key: http://localhost:8080/realms/patient-risk
        algorithm: RS256
        rsa_public_key: |
          -----BEGIN PUBLIC KEY-----
          MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAvgTs9Wjq3vEcUBnWODEV
          8Qhauhasju4bdPymVlqti2KLWKyjk7zog3P6lrG8/W+6UsIcIzR2QOQdammxBaWu
          C2TDaUvqYKwiYRsYkVhREdblGn9jZXGxppZO1J6HPnClQ+6uRsAvCLumyIa5k5ml
          AtF5jEwhUPghTOowsPxsCGMG0cgOnX7Xf4InMTchBiTgUDJirdIQEezLXAt/ghoP
          9sf9GrFKjJWfl1WPDFSltPZWhHiA/xXMHoEBPTSSaEcjtYNmyjxwTUVA9vEm7TX5
          ardJM0X1oo03zyGx/JBWhqP/NzNl1nhCSa6qa++23l2Nl5n0W3TTC3lTTDN8QLzJ
          RwIDAQAB
          -----END PUBLIC KEY-----
